//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtdK22CNT3Lesson10.Views.PtdAccounts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTDK22CNT3Lesson10Entities1 : DbContext
    {
        public PTDK22CNT3Lesson10Entities1()
            : base("name=PTDK22CNT3Lesson10Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PtdAccount> PtdAccount { get; set; }
    }
}
