//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtdK22CNT3Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtdAccount
    {
        public int PtdId { get; set; }
        public string PtdUserName { get; set; }
        public string PtdPassword { get; set; }
        public string PtdFullName { get; set; }
        public string PtdEmail { get; set; }
        public string PtdPhone { get; set; }
        public Nullable<bool> PtdActive { get; set; }
    }
}
